#include "PFFSource.h"

registerMooseObject("reproductionApp", PFFSource);

InputParameters
PFFSource::validParams()
{
  InputParameters params = Kernel::validParams();
  params.addClassDescription(
      "Adds a source term of the form (test, d(psi)/d(variable)) using derivative material "
      "properties generated by a derivative parsed free energy material.");
  params.addParam<MaterialPropertyName>(
      "free_energy", "psi", "Name of the Helmholtz free energy material property");
  params.addParam<MaterialPropertyName>(
      "dpsi_dd", "dpsi_dd", "Material property for d(free_energy)/d(variable)");
  params.addParam<MaterialPropertyName>(
      "d2psi_dd2", "d2psi_dd2", "Material property for d^2(free_energy)/d(variable)^2");
  return params;
}

PFFSource::PFFSource(const InputParameters & parameters)
  : Kernel(parameters),
    _dpsi_dd(getMaterialProperty<Real>(getParam<MaterialPropertyName>("dpsi_dd"))),
    _d2psi_dd2(getMaterialProperty<Real>(getParam<MaterialPropertyName>("d2psi_dd2")))
{
}

Real
PFFSource::computeQpResidual()
{
  return _test[_i][_qp] * _dpsi_dd[_qp];
}

Real
PFFSource::computeQpJacobian()
{
  return _test[_i][_qp] * _d2psi_dd2[_qp] * _phi[_j][_qp];
}
